name: Test Dataloader
on:
  repository_dispatch:
    types: [test-command]
jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.pull_request.head.sha }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64
        cache: 'pip'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run nusantara tests
      id: nusantara_test
      continue-on-error: true
      env:
        DATASET_NAME: ${{ github.event.client_payload.slash_command.args.named.dataset }}
        SUBSET_ID: ${{ github.event.client_payload.slash_command.args.named.subset_id }}
      run: |
       if [-z "${{ env.SUBSET_ID }}"]
       then
          echo "not defined"
        else
          echo "defined"
       fi
       command=python -m tests.test_nusantara nusantara/nusa_datasets/${{ env.DATASET_NAME }}/${{ env.DATASET_NAME }}.py
       echo "::set-output name=run_url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
    - name: Add comment result
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.client_payload.pull_request.number }}
        body: |
          ### Run result
          Check test log here: ${{ steps.nusantara_test.outputs.run_url}}

